# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  config.vm.box = "geerlingguy/centos7"

  config.ssh.insert_key = false
  
  config.vm.synced_folder ".","/vagrant", disabled: true

  config.vm.provider :virtualbox do |v| 
    v.memory = 256
    v.linked_clone = true
  end

  # App server 1
  config.vm.define "ec2" do |ec2|
    ec2.vm.hostname = "orc-ec2.test"
    ec2.vm.network :private_network, ip: "192.168.60.4"
  end

end
